/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import scene from "../Assets/Models/PortFolioRock.glb"

const Rocks = ({ ...props }) =>  {
    const { nodes, materials } = useGLTF(scene)
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={materials['Material.002']}
            />
        </group>
    )
}

export default Rocks;
